# Generated by Django 4.0.4 on 2022-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(null=True)),
                ('message_from_id', models.BigIntegerField()),
                ('message_chat_id', models.BigIntegerField(null=True)),
                ('inlinequery_id', models.BigIntegerField(null=True)),
                ('callbackquery_id', models.BigIntegerField(null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('message_text', models.CharField(max_length=2000, null=True)),
                ('message_date', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('processed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('first_message_time', models.DateTimeField(auto_now=True)),
                ('last_active_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
