# Generated by Django 4.0.4 on 2022-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_basket_basketposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
    ]
