# Generated by Django 4.0.4 on 2022-06-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_basketposition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketposition',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='market.user'),
        ),
    ]
